
# Basketball offensive stats

# Priotiry 1
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Field goals made', 'field_goals_made', 'field_goals_attempted', 'basketball', 'FGM', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Field goals attempted', 'field_goals_attempted', NULL, 'basketball', 'FGA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Field goal %', 'field_goals_percentage', NULL, 'basketball', 'FG%', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', '3pt field goals made', 'three_pointers_made', 'three_pointers_attempted', 'basketball', '3PM', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', '3pt field goals attempted', 'three_pointers_attempted', NULL, 'basketball', '3PA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', '3pt field goal %', 'three_pointers_percentage', NULL, 'basketball', '3P%', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Free throws made', 'free_throws_made', 'free_throws_attempted', 'basketball', 'FTM', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Free throws attempted', 'free_throws_attempted', NULL, 'basketball', 'FTA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Free throw %', 'free_throws_percentage', NULL, 'basketball', 'FT%', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Points total', 'points_scored_total', NULL, 'basketball', 'PTS', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Points per game', 'points_scored_per_game', NULL, 'basketball', 'PPG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Assists', 'assists_total', NULL, 'basketball', 'AST', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Assists per game', 'assists_per_game', NULL, 'basketball', 'APG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Offensive rebounds per game', 'rebounds_offensive_per_game', NULL, 'basketball', 'ORB', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Offensive rebounds', 'rebounds_offensive', NULL, 'basketball', 'ORB', 3);

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Turnovers', 'turnovers_total', NULL, 'basketball', 'TO', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Turnovers per game', 'turnovers_per_game', NULL, 'basketball', 'TO/G', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Rebounds total', 'rebounds_total', NULL, 'basketball', 'RB', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Rebounds per game', 'rebounds_per_game', NULL, 'basketball', 'RPG', 1);


# Basketball defensive stats

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_defensive_stat', 'Defensive rebounds per game', 'rebounds_defensive_per_game', NULL, 'basketball', 'DRB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_defensive_stat', 'Defensive rebounds total', 'rebounds_defensive', NULL, 'basketball', 'DRB Tot', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Steals per game', 'steals_per_game', NULL, 'basketball', 'SPG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Steals total', 'steals_total', NULL, 'basketball', 'STL', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Blocks per game', 'blocks_per_game', NULL, 'basketball', 'BPG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Blocks total', 'blocks_total', NULL, 'basketball', 'BLK', 1);




