

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_defensive_stats', 'baseball_stat', 'Errors', 'errors', NULL, 'baseball', 'E', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Average', 'average', NULL, 'baseball', 'AVG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Runs scored', 'runs_scored', NULL, 'baseball', 'R', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'At bats', 'at_bats', NULL, 'baseball', 'AB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Hits', 'hits', NULL, 'baseball', 'H', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Runs batted in', 'rbi', NULL, 'baseball', 'RBI', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Total bases', 'total_bases', NULL, 'baseball', 'TB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Slugging percentage', 'slugging_percentage', NULL, 'baseball', 'SLG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Bases on balls', 'bases_on_balls', NULL, 'baseball', 'BB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Batting Strikeouts', 'strikeouts', NULL, 'baseball', 'SO', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Singles', 'singles', NULL, 'baseball', '1B', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Doubles', 'doubles', NULL, 'baseball', '2B', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Triples', 'triples', NULL, 'baseball', '3B', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Home runs', 'home_runs', NULL, 'baseball', 'HR', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Grand slams', 'grand_slams', NULL, 'baseball', 'GS', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Stolen bases', 'stolen_bases', NULL, 'baseball', 'SB', 1);

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Wins', 'wins', NULL, 'baseball', 'W', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Losses', 'losses', NULL, 'baseball', 'L', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Earned runs against', 'era', NULL, 'baseball', 'ERA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Complete games', 'games_complete', NULL, 'baseball', 'CG', 1);  
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Shutouts', 'shutouts', NULL, 'baseball', 'SHO', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Innings pitched', 'innings_pitched', NULL, 'baseball', 'IP', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Hits', 'hits', NULL, 'baseball', 'H', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Earned runs', 'earned_runs', NULL, 'baseball', 'ER', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Unearned runs', 'unearned_runs', NULL, 'baseball', 'UnER', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Home runs allowed', 'home_runs_allowed', NULL, 'baseball', 'HR', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Bases on balls', 'bases_on_balls', NULL, 'baseball', 'BB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Hit batters', 'errors_hit_with_pitch', NULL, 'baseball', 'HB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Pitching Strikeouts', 'strikeouts', NULL, 'baseball', 'SO', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Saves', 'saves', NULL, 'baseball', 'S', 1);

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Runs allowed', 'runs_allowed', NULL, 'baseball', 'RA', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Singles allowed', 'singles_allowed', NULL, 'baseball', '1A', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Doubles allowed', 'doubles_allowed', NULL, 'baseball', '2A', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Triples allowed', 'triples_allowed', NULL, 'baseball', '3A', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Pitches thrown', 'number_of_pitches', NULL, 'baseball', 'PT', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Pick offs', 'pick_offs', NULL, 'baseball', 'PO', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Finished games', 'games_finished', NULL, 'baseball', 'GF', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_pitching_stat', 'Winning percentage', 'winning_percentage', NULL, 'baseball', 'W %', 2);

