
# Basketball offensive stats

# Priotiry 1
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (1, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Field goal %', 'field_goals_percentage', NULL, 'basketball', 'FG%', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (2, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', '3pt field goal %', 'three_pointers_percentage', NULL, 'basketball', '3%', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (3, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Free throw %', 'free_throws_percentage', NULL, 'basketball', 'FT%', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (4, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Points total', 'points_scored_total', NULL, 'basketball', 'P', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (5, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Points per game', 'points_scored_per_game', NULL, 'basketball', 'PPG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (6, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Assists total', 'assists_total', NULL, 'basketball', 'ASS', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (7, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Offensive Rebounds per game', 'rebounds_offensive_per_game', NULL, 'basketball', 'ORB', 2);


INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (8, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Free throws made', 'free_throws_made', 'free_throws_attempted', 'basketball', 'FTM/FTA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (9, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', '3pt field goals made', 'three_pointers_made', 'three_pointers_attempted', 'basketball', '3PM/3PA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (10, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Field goals made', 'field_goals_made', 'field_goals_attempted', 'basketball', 'FGM/FGA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (11, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Assists per game', 'assists_per_game', NULL, 'basketball', 'APG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (12, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Offensive Rebounds total', 'rebounds_defensive', NULL, 'basketball', 'ORB', 3);


# Priority 3
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (13, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Field goal % adjusted', 'field_goal_percentage_adjusted', NULL, 'basketball', 'FG% Adj', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (14, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Turnovers', 'turnovers_total', NULL, 'basketball', 'TO', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (15, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Turnovers per game', 'turnovers_per_game', NULL, 'basketball', 'TO/G', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (16, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Points scored off turnovers', 'points_scored_off_turnovers', NULL, 'basketball', 'TO Pts', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (17, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Points scored in paint', 'points_scored_in_paint', NULL, 'basketball', 'P in Paint', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (18, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Second chance points', 'points_scored_on_second_chance', NULL, 'basketball', '2nd pts', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (19, CURDATE(), CURDATE(), 'basketball_offensive_stats', 'basketball_offensive_stat', 'Fast break points', 'points_scored_on_fast_break', NULL, 'basketball', 'FB Pts', 3);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (20, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Rebounds total', 'rebounds_total', NULL, 'basketball', 'RB', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (21, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_offensive_stat', 'Rebounds per game', 'rebounds_per_game', NULL, 'basketball', 'RPG', 1);


# Basketball defensive stats

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (22, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_defensive_stat', 'Defensive rebounds per game', 'rebounds_defensive_per_game', NULL, 'basketball', 'DRB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (23, CURDATE(), CURDATE(), 'basketball_rebounding_stats', 'basketball_defensive_stat', 'Defensive rebounds total', 'rebounds_defensive', NULL, 'basketball', 'DRB Tot', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (24, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Steals per game', 'steals_per_game', NULL, 'basketball', 'SPG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (25, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Steals Total', 'steals_total', NULL, 'basketball', 'STL', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (26, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Blocks per game', 'blocks_per_game', NULL, 'basketball', 'BPG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (27, CURDATE(), CURDATE(), 'basketball_defensive_stats', 'basketball_defensive_stat', 'Blocks total', 'blocks_total', NULL, 'basketball', 'BLK', 1);




