

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (107, NOW(), NOW(), 'baseball_defensive_stats', 'baseball_stat', 'Errors', 'errors', NULL, 'baseball', 'E', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (108, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Average', 'average', NULL, 'baseball', 'AVG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (109, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Runs scored', 'runs_scored', NULL, 'baseball', 'R', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (110, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'At bats', 'at_bats', NULL, 'baseball', 'AB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (111, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Hits', 'hits', NULL, 'baseball', 'H', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (112, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Runs batted in', 'rbi', NULL, 'baseball', 'RBI', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (113, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Total bases', 'total_bases', NULL, 'baseball', 'TB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (114, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Slugging percentage', 'slugging_percentage', NULL, 'baseball', 'SLG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (115, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Bases on balls', 'bases_on_balls', NULL, 'baseball', 'BB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (116, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Strikeouts', 'strikeouts', NULL, 'baseball', 'SO', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (117, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Runs scored', 'runs_scored', NULL, 'baseball', 'R', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (118, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Singles', 'singles', NULL, 'baseball', '1B', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (119, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Doubles', 'doubles', NULL, 'baseball', '2B', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (120, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Triples', 'triples', NULL, 'baseball', '3B', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (121, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Home runs', 'home_runs', NULL, 'baseball', 'HR', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (122, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Grand slams', 'grand_slams', NULL, 'baseball', 'GS', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (123, NOW(), NOW(), 'baseball_offensive_stats', 'baseball_stat', 'Stolen bases', 'stolen_bases', NULL, 'baseball', 'SB', 1);

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (124, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Runs allowed', 'runs_allowed', NULL, 'baseball', 'RA', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (125, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Singles allowed', 'singles_allowed', NULL, 'baseball', '1A', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (126, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Doubles allowed', 'doubles_allowed', NULL, 'baseball', '2A', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (127, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Triples allowed', 'triples_allowed', NULL, 'baseball', '3A', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (128, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Home runs allowed', 'home_runs_allowed', NULL, 'baseball', 'HRA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (129, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Innings pitched', 'innings_pitched', NULL, 'baseball', 'IP', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (130, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Hits', 'hits', NULL, 'baseball', 'H', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (131, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Earned runs', 'earned_runs', NULL, 'baseball', 'ER', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (132, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Unearned runs', 'unearned_runs', NULL, 'baseball', 'UER', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (133, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Bases on balls', 'bases_on_balls', NULL, 'baseball', 'BB', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (134, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Strikeouts', 'strikeouts', NULL, 'baseball', 'SO', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (135, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Pitches thrown', 'number_of_pitches', NULL, 'baseball', 'PT', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (136, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'ERA', 'era', NULL, 'baseball', 'ERA', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (137, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Pick offs', 'pick_offs', NULL, 'baseball', 'PO', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (138, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Wins', 'wins', NULL, 'baseball', 'W', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (139, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Loses', 'loses', NULL, 'baseball', 'L', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (140, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Saves', 'saves', NULL, 'baseball', 'S', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (141, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Shutouts', 'shoutouts', NULL, 'baseball', 'SHO', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (142, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Complete games', 'games_complete', NULL, 'baseball', 'CG', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (143, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Finished games', 'games_finished', NULL, 'baseball', 'GF', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (144, NOW(), NOW(), 'baseball_pitching_stats', 'baseball_stat', 'Winning percentage', 'winning_percentage', NULL, 'baseball', 'W %', 1);

