# Professional Leagues
UPDATE display_names SET abbreviation="MLB" WHERE full_name="Major League Baseball";
UPDATE display_names SET abbreviation="NBA" WHERE full_name="National Basketball Association";
UPDATE display_names SET abbreviation="NFL" WHERE full_name="National Football League";
UPDATE display_names SET abbreviation="NHL" WHERE full_name="National Hockey League";

#Professional Divisions
UPDATE display_names SET abbreviation="Central" WHERE full_name="AL Central";
UPDATE display_names SET first_name="AL Central" WHERE full_name="AL Central";
UPDATE display_names SET last_name="Division" WHERE full_name="AL Central";
UPDATE display_names SET abbreviation="AL Central Division" WHERE full_name="AL Central";
UPDATE display_names SET abbreviation="East" WHERE full_name="AL East";
UPDATE display_names SET first_name="AL East" WHERE full_name="AL East";
UPDATE display_names SET last_name="Division" WHERE full_name="AL East";
UPDATE display_names SET last_name="AL East Division" WHERE full_name="AL East";
UPDATE display_names SET abbreviation="West" WHERE full_name="AL West";
UPDATE display_names SET first_name="AL West" WHERE full_name="AL West";
UPDATE display_names SET last_name="Division" WHERE full_name="AL West";
UPDATE display_names SET last_name="AL West Division" WHERE full_name="AL West";
UPDATE display_names SET abbreviation="Central" WHERE full_name="NL Central";
UPDATE display_names SET first_name="NL Central" WHERE full_name="NL Central";
UPDATE display_names SET last_name="Division" WHERE full_name="NL Central";
UPDATE display_names SET abbreviation="NL Central Division" WHERE full_name="NL Central";
UPDATE display_names SET abbreviation="East" WHERE full_name="NL East";
UPDATE display_names SET first_name="NL East" WHERE full_name="NL East";
UPDATE display_names SET last_name="Division" WHERE full_name="NL East";
UPDATE display_names SET last_name="NL East Division" WHERE full_name="NL East";
UPDATE display_names SET abbreviation="West" WHERE full_name="NL West";
UPDATE display_names SET first_name="NL West" WHERE full_name="NL West";
UPDATE display_names SET last_name="Division" WHERE full_name="NL West";
UPDATE display_names SET last_name="NL West Division" WHERE full_name="NL West";
UPDATE display_names SET abbreviation="Atantic" WHERE full_name="Atlantic";
UPDATE display_names SET first_name="Atlantic" WHERE full_name="Atlantic";
UPDATE display_names SET last_name="Division" WHERE full_name="Atlantic";
UPDATE display_names SET last_name="Atlantic Division" WHERE full_name="Atlantic";
UPDATE display_names SET abbreviation="Central" WHERE full_name="Central";
UPDATE display_names SET first_name="Central" WHERE full_name="Central";
UPDATE display_names SET last_name="Division" WHERE full_name="Central";
UPDATE display_names SET last_name="Central Division" WHERE full_name="Central";
UPDATE display_names SET abbreviation="Southeast" WHERE full_name="Southeast";
UPDATE display_names SET first_name="Southeast" WHERE full_name="Southeast";
UPDATE display_names SET last_name="Division" WHERE full_name="Southeast";
UPDATE display_names SET last_name="Southeast Division" WHERE full_name="Southeast";
UPDATE display_names SET abbreviation="Northwest" WHERE full_name="Northwest";
UPDATE display_names SET first_name="Northwest" WHERE full_name="Northwest";
UPDATE display_names SET last_name="Division" WHERE full_name="Northwest";
UPDATE display_names SET last_name="Northwest Division" WHERE full_name="Northwest";
UPDATE display_names SET abbreviation="Pacific" WHERE full_name="Pacific";
UPDATE display_names SET first_name="Pacific" WHERE full_name="Pacific";
UPDATE display_names SET last_name="Division" WHERE full_name="Pacific";
UPDATE display_names SET last_name="Pacific Division" WHERE full_name="Pacific";
UPDATE display_names SET abbreviation="Southwest" WHERE full_name="Southwest";
UPDATE display_names SET first_name="Southwest" WHERE full_name="Southwest";
UPDATE display_names SET last_name="Division" WHERE full_name="Southwest";
UPDATE display_names SET last_name="Southwest Division" WHERE full_name="Southwest";
UPDATE display_names SET abbreviation="East" WHERE full_name="AFC East";
UPDATE display_names SET first_name="AFC East" WHERE full_name="AFC East";
UPDATE display_names SET last_name="Division" WHERE full_name="AFC East";
UPDATE display_names SET last_name="AFC East Division" WHERE full_name="AFC East";
UPDATE display_names SET abbreviation="East" WHERE full_name="AFC North";
UPDATE display_names SET first_name="AFC North" WHERE full_name="AFC North";
UPDATE display_names SET last_name="Division" WHERE full_name="AFC North";
UPDATE display_names SET last_name="AFC North Division" WHERE full_name="AFC North";
UPDATE display_names SET abbreviation="East" WHERE full_name="AFC South";
UPDATE display_names SET first_name="AFC South" WHERE full_name="AFC South";
UPDATE display_names SET last_name="Division" WHERE full_name="AFC South";
UPDATE display_names SET last_name="AFC South Division" WHERE full_name="AFC South";
UPDATE display_names SET abbreviation="East" WHERE full_name="AFC West";
UPDATE display_names SET first_name="AFC West" WHERE full_name="AFC West";
UPDATE display_names SET last_name="Division" WHERE full_name="AFC West";
UPDATE display_names SET last_name="AFC West Division" WHERE full_name="AFC West";
UPDATE display_names SET abbreviation="East" WHERE full_name="NFC East";
UPDATE display_names SET first_name="NFC East" WHERE full_name="NFC East";
UPDATE display_names SET last_name="Division" WHERE full_name="NFC East";
UPDATE display_names SET last_name="NFC East Division" WHERE full_name="NFC East";
UPDATE display_names SET abbreviation="East" WHERE full_name="NFC North";
UPDATE display_names SET first_name="NFC North" WHERE full_name="NFC North";
UPDATE display_names SET last_name="Division" WHERE full_name="NFC North";
UPDATE display_names SET last_name="NFC North Division" WHERE full_name="NFC North";
UPDATE display_names SET abbreviation="East" WHERE full_name="NFC South";
UPDATE display_names SET first_name="NFC South" WHERE full_name="NFC South";
UPDATE display_names SET last_name="Division" WHERE full_name="NFC South";
UPDATE display_names SET last_name="NFC South Division" WHERE full_name="NFC South";
UPDATE display_names SET abbreviation="East" WHERE full_name="NFC West";
UPDATE display_names SET first_name="NFC West" WHERE full_name="NFC West";
UPDATE display_names SET last_name="Division" WHERE full_name="NFC West";
UPDATE display_names SET last_name="NFC West Division" WHERE full_name="NFC West";
UPDATE display_names SET abbreviation="Northeast" WHERE full_name="Northeast Conference";
UPDATE display_names SET first_name="Northeast" WHERE full_name="Northeast Conference";
UPDATE display_names SET last_name="Division" WHERE full_name="Northeast Conference";
UPDATE display_names SET last_name="Northeast Division" WHERE full_name="Northeast Conference";


# College leagues
UPDATE display_names SET abbreviation="M Bskt" WHERE full_name="NCAA Men's Basketball Division 1";
UPDATE display_names SET abbreviation="D1AA FB" WHERE full_name="NCAA Men's Football Division 1AA";
UPDATE display_names SET abbreviation="D1A FB" WHERE full_name="NCAA Men's Football Division 1A";
UPDATE display_names SET abbreviation="D2 FB" WHERE full_name="NCAA Men's Football Division 2";
UPDATE display_names SET abbreviation="D3 FB" WHERE full_name="NCAA Men's Football Division 3";
UPDATE display_names SET abbreviation="D1 Bball" WHERE full_name="NCAA Men's Baseball";
UPDATE display_names SET abbreviation="W Bskt" WHERE full_name="NCAA Women's Basketball Division 1";

# D1A FB college conferences
UPDATE display_names SET abbreviation="ACC" WHERE full_name="Atlantic Coast Conference";
UPDATE display_names SET first_name="Atlantic Coast" WHERE full_name="Atlantic Coast Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Atlantic Coast Conference";
UPDATE display_names SET abbreviation="Big 10" WHERE full_name="Big 10 Conference";
UPDATE display_names SET first_name="Big 10" WHERE full_name="Big 10 Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Big 10 Conference";
UPDATE display_names SET abbreviation="Big 12" WHERE full_name="Big 12 Conference";
UPDATE display_names SET first_name="Big 12" WHERE full_name="Big 12 Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Big 12 Conference";
UPDATE display_names SET abbreviation="Big East" WHERE full_name="Big East Conference";
UPDATE display_names SET first_name="Big East" WHERE full_name="Big East Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Big East Conference";
UPDATE display_names SET abbreviation="USA" WHERE full_name="Conference USA";
UPDATE display_names SET first_name="USA" WHERE full_name="Conference USA";
UPDATE display_names SET last_name="Conference" WHERE full_name="Conference USA";
UPDATE display_names SET abbreviation="1A Ind" WHERE full_name="Division 1A Independents";
UPDATE display_names SET first_name="1A Independents" WHERE full_name="Division 1A Independents";
UPDATE display_names SET last_name="Division" WHERE full_name="Division 1A Independents";
UPDATE display_names SET abbreviation="MAC" WHERE full_name="Mid-American Conference";
UPDATE display_names SET first_name="Mid-America" WHERE full_name="Mid-American Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Mid-American Conference";
UPDATE display_names SET abbreviation="MWC" WHERE full_name="Mountain West Conference";
UPDATE display_names SET first_name="Mountain West" WHERE full_name="Mountain West Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Mountain West Conference";
UPDATE display_names SET abbreviation="Pac-10" WHERE full_name="Pacific-10 Conference";
UPDATE display_names SET first_name="Pacific-10" WHERE full_name="Pacific-10 Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Pacific-10 Conference";
UPDATE display_names SET abbreviation="SEC" WHERE full_name="Southeastern Conference";
UPDATE display_names SET first_name="Southeastern" WHERE full_name="Southeastern Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Southeastern Conference";
UPDATE display_names SET abbreviation="Sun Belt" WHERE full_name="Sun Belt Conference";
UPDATE display_names SET first_name="Sun Belt" WHERE full_name="Sun Belt Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Sun Belt Conference";
UPDATE display_names SET abbreviation="WAC" WHERE full_name="Western Athletic Conference";
UPDATE display_names SET first_name="Western Athletic" WHERE full_name="Western Athletic Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Western Athletic Conference";

# D1AA FB College conferences
UPDATE display_names SET abbreviation="Big Sky" WHERE full_name="Big Sky Conference";
UPDATE display_names SET first_name="Big Sky" WHERE full_name="Big Sky Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Big Sky Conference";
UPDATE display_names SET abbreviation="Big South" WHERE full_name="Big South Conference";
UPDATE display_names SET first_name="Big South" WHERE full_name="Big South Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Big South Conference";
UPDATE display_names SET abbreviation="CAA" WHERE full_name="Colonial";
UPDATE display_names SET first_name="Colonial Athletic" WHERE full_name="Colonial";
UPDATE display_names SET last_name="Association" WHERE full_name="Colonial";
UPDATE display_names SET full_name="Colonial Athletic Association" WHERE full_name="Colonial";
UPDATE display_names SET abbreviation="1AA Ind" WHERE full_name="Division 1AA Independents";
UPDATE display_names SET first_name="1AA Independents" WHERE full_name="Division 1AA Independents";
UPDATE display_names SET last_name="Division" WHERE full_name="Division 1AA Independents";
UPDATE display_names SET abbreviation="G. West" WHERE full_name="Great West Conference";
UPDATE display_names SET first_name="Great West" WHERE full_name="Great West Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Great West Conference";
UPDATE display_names SET abbreviation="Ivy L." WHERE full_name="Ivy League";
UPDATE display_names SET first_name="Ivy" WHERE full_name="Ivy League";
UPDATE display_names SET last_name="League" WHERE full_name="Ivy League";
UPDATE display_names SET abbreviation="MAAC" WHERE full_name="Metro Atlantic Athletic Conference";
UPDATE display_names SET first_name="Metro Atlantic Athletic" WHERE full_name="Metro Atlantic Athletic Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Metro Atlantic Athletic Conference";
UPDATE display_names SET abbreviation="MEAC" WHERE full_name="Mid Eastern Athletic Conference";
UPDATE display_names SET first_name="Mid Eastern Athletic" WHERE full_name="Mid Eastern Athletic Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Mid Eastern Athletic Conference";
UPDATE display_names SET abbreviation="MEAC" WHERE full_name="Mid Eastern Athletic Conference";
UPDATE display_names SET first_name="Mid Eastern Athletic" WHERE full_name="Mid Eastern Athletic Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Mid Eastern Athletic Conference";
UPDATE display_names SET abbreviation="MVFC" WHERE full_name="Missouri Valley Football Conference";
UPDATE display_names SET first_name="Missouri Valley Football" WHERE full_name="Missouri Valley Football Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Missouri Valley Football Conference";
UPDATE display_names SET abbreviation="NEC" WHERE full_name="Northest Conference";
UPDATE display_names SET first_name="Northeast" WHERE full_name="Northeast Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Northeast Conference";
UPDATE display_names SET abbreviation="OVC" WHERE full_name="Ohio Valley Conference";
UPDATE display_names SET first_name="Ohio Valley" WHERE full_name="Ohio Valley Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="ohio Valley Conference";
UPDATE display_names SET abbreviation="Patriot" WHERE full_name="Patriot League";
UPDATE display_names SET first_name="Patriot" WHERE full_name="Patriot League";
UPDATE display_names SET last_name="League" WHERE full_name="Patriot League";
UPDATE display_names SET abbreviation="PFL" WHERE full_name="Pioneer League";
UPDATE display_names SET first_name="Pioneer" WHERE full_name="Pioneer League";
UPDATE display_names SET last_name="League" WHERE full_name="Pioneer League";
UPDATE display_names SET full_name="Pioneer Football League" WHERE full_name="Pioneer League";
UPDATE display_names SET abbreviation="SoCon" WHERE full_name="Southern Conference";
UPDATE display_names SET first_name="Southern" WHERE full_name="Southern Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Southern Confernce";
UPDATE display_names SET abbreviation="Southland" WHERE full_name="Southland Conference";
UPDATE display_names SET first_name="Southland" WHERE full_name="Southland Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Southland Confernce";
UPDATE display_names SET abbreviation="SWAC" WHERE full_name="Southwestern Athletic Conference";
UPDATE display_names SET first_name="Southwestern" WHERE full_name="Southwestern Athletic Conference";
UPDATE display_names SET last_name="Conference" WHERE full_name="Southwestern Athletic Confernce";

# Other D1 Conferences
UPDATE display_names SET abbreviation='A. East' WHERE full_name='America East Conference';
UPDATE display_names SET first_name='America East' WHERE full_name='America East Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='America East Conference';
UPDATE display_names SET abbreviation='A-10' WHERE full_name='Atlantic 10 Conference';
UPDATE display_names SET first_name='Atlantic 10' WHERE full_name='Atlantic 10 Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='Atlantic 10 Conference';
UPDATE display_names SET abbreviation='A-Sun' WHERE full_name='Atlantic Sun Conference';
UPDATE display_names SET first_name='Atlantic Sun' WHERE full_name='Atlantic Sun Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='Atlantic Sun Conference';
UPDATE display_names SET abbreviation='Big 10' WHERE full_name='Big Ten Conference';
UPDATE display_names SET first_name='Big 10' WHERE full_name='Big Ten Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='Big Ten Conference';
UPDATE display_names SET full_name='Big 10 Conference' WHERE full_name='Big Ten Conference';
UPDATE display_names SET abbreviation='Big 12' WHERE full_name='Big Twelve Conference';
UPDATE display_names SET first_name='Big 12' WHERE full_name='Big Twelve Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='Big Twelve Conference';
UPDATE display_names SET full_name='Big 12 Conference' WHERE full_name='Big Twelve Conference';
UPDATE display_names SET abbreviation='Big West' WHERE full_name='Big West Conference';
UPDATE display_names SET first_name='Big West' WHERE full_name='Big West Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='Big West Conference';
UPDATE display_names SET abbreviation='CAA' WHERE full_name='Colonial Athletic Association';
UPDATE display_names SET first_name='Colonial Athletic' WHERE full_name='Colonial Athletic Association';
UPDATE display_names SET last_name='Association' WHERE full_name='Colonial Athletic Association';
UPDATE display_names SET abbreviation='' WHERE full_name='Division I Independent';
UPDATE display_names SET first_name='' WHERE full_name='Division I Independent';
UPDATE display_names SET last_name='Conference' WHERE full_name='Division I Independent';
UPDATE display_names SET abbreviation='Ind  ' WHERE full_name='Division I Independent';
UPDATE display_names SET first_name='Division I' WHERE full_name='Division I Independent';
UPDATE display_names SET last_name='Independents' WHERE full_name='Division I Independent';
UPDATE display_names SET last_name='Division I Independents' WHERE full_name='Division I Independent';
UPDATE display_names SET abbreviation='Horizon' WHERE full_name='Horizon League';
UPDATE display_names SET first_name='Horizon' WHERE full_name='Horizon League';
UPDATE display_names SET last_name='League' WHERE full_name='Horizon League';
UPDATE display_names SET abbreviation='Summit' WHERE full_name='Summit League';
UPDATE display_names SET first_name='Summit' WHERE full_name='Summit League';
UPDATE display_names SET last_name='League' WHERE full_name='Summit League';
UPDATE display_names SET abbreviation='WCC' WHERE full_name='West Coast Conference';
UPDATE display_names SET first_name='West Coast' WHERE full_name='West Coast Conference';
UPDATE display_names SET last_name='Conference' WHERE full_name='West Coast Conference';

