
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Tackles', 'tackles_total', NULL, 'american football', 'T', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Interceptions', 'interceptions_total', NULL, 'american football', 'INT', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Interception yards', 'interceptions_yards', NULL, 'american football', 'INT YD', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Interception average', 'interceptions_average', NULL, 'american football', 'INT', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Interception touchdowns', 'interceptions_touchdown', NULL, 'american football', 'INT TD', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Quarterback hurries', 'quarterback_hurries', NULL, 'american football', 'HUR', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Sacks', 'sacks_total', NULL, 'american football', 'S', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_defensive_stats', 'american_football_defensive_stat', 'Sack yards', 'sacks_yards', NULL, 'american football', 'S YD', 2);


INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_fumbles_stats', 'american_football_offensive_stat', 'Fumbles', 'fumbles_committed', NULL, 'american football', 'FUM', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_fumbles_stats', 'american_football_defensive_stat', 'Forced fumbles', 'fumbles_forced', NULL, 'american football', 'FF', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_fumbles_stats', 'american_football_defensive_stat', 'Fumbles recovered', 'fumbles_recovered', NULL, 'american football', 'FR', 2);

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_offensive_stats', 'american_football_offensive_stat', 'Average yards per play', 'offensive_plays_average_yards_per', NULL, 'american football', 'FF', 2);


INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Completions', 'passes_completions', 'passes_attempts', 'american football', 'COM/ATT', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Passing percentage', 'passes_percentage', NULL, 'american football', 'P %', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Passing yards', 'passes_yards_gross', NULL, 'american football', 'P YD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Completion percentage', 'passes_percentage', NULL, 'american football', 'P %', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Passing touchdowns', 'passes_touchdowns', NULL, 'american football', 'P TD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Interceptions thrown', 'passes_interceptions', NULL, 'american football', 'INT', 1); 
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Longest completion', 'passes_longest', NULL, 'american football', 'LG COM', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Yards per completion', 'passes_average_yards_per', NULL, 'american football', 'AVE COM', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Passer rating', 'passer_rating', NULL, 'american football', 'RAT', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Receptions', 'receptions_total', NULL, 'american football', 'REC', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Reception yards', 'receptions_yards', NULL, 'american football', 'REC YD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Receiving touchdowns', 'receptions_touchdowns', NULL, 'american football', 'REC TD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Longest reception', 'receptions_longest', NULL, 'american football', 'LG REC', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_passing_stats', 'american_football_offensive_stat', 'Yards per recptiones', 'receptions_average_yards_per', NULL, 'american football', 'AVE REC', 1);

INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_rushing_stats', 'american_football_offensive_stat', 'Rushing attempts', 'rushes_attempts', NULL, 'american football', 'RSH ATT', 2);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_rushing_stats', 'american_football_offensive_stat', 'Rushing yards', 'rushes_yards', NULL, 'american football', 'RSH YD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_rushing_stats', 'american_football_offensive_stat', 'Rushing touchdowns', 'rushes_touchdowns', NULL, 'american football', 'RSH TD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_rushing_stats', 'american_football_offensive_stat', 'Yards per rush', 'rushing_average_yards_per', NULL, 'american football', 'RSH YD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_rushing_stats', 'american_football_offensive_stat', 'Longest rush', 'rushes_longest', NULL, 'american football', 'LG RSH', 2);


INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_scoring_stats', 'american_football_offensive_stat', 'Touchdowns', 'touchdowns_total', NULL, 'american football', 'TD', 1);
INSERT INTO stats_mappings (`id`, `created_at`, `updated_at`, `stats_table`, `stats_type`, `stats_name`, `stats_field`, `counter_field`, `sport`, `abbreviation`, `priority`) VALUES (NULL, NOW(), NOW(), 'american_football_scoring_stats', 'american_football_offensive_stat', 'Field goals', 'field_goals_made', 'field_goal_attempts', 'american football', 'FG/ATT', 1);


